<?php
/** @var $block \ONVO\Pay\Block\Adminhtml\Order\View\Info */
$_order = $block->getOrder();
$payment = $_order->getPayment();
?>
<?php if ($payment): ?>
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__(ucfirst($payment->getMethod()))) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php
        $ad = $payment->getAdditionalInformation();
        if (isset($ad['transaction_result'])) {
            foreach (json_decode($ad['transaction_result'], true) as $key => $val) {
                echo "<p><strong>{$key}:</strong> {$val}</p>";
            }
        }
        ?>
    </div>
<?php endif; ?>
